### ISSUE TITLE
The package does not install on macOS with sudo

### ISSUE THREAD

**Issue by enzocano** [olydis/dotnet-runtime#2]
I get the following message if i try to install the tool with `sudo npm i -g dotnet-2.0.0`

```
$ sudo npm i -g dotnet-2.0.0
/Users/travis/.nvm/versions/node/v10.9.0/bin/dotnet -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/call.js
/Users/travis/.nvm/versions/node/v10.9.0/bin/dotnet-run -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/call.js
/Users/travis/.nvm/versions/node/v10.9.0/bin/dotnet-run-2.0.0 -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/call.js
/Users/travis/.nvm/versions/node/v10.9.0/bin/install-dotnet-runtime -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/app.js
> dotnet-2.0.0@1.4.4 postinstall /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/travis/.nvm/versions/node/v10.9.0/bin/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dotnet-2.0.0@1.4.4 postinstall: `node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dotnet-2.0.0@1.4.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/travis/.npm/_logs/2018-09-05T17_07_40_995Z-debug.log
```

If I use `npm i -g dotnet-2.0.0`, the tool works fine.

```
$ npm i -g dotnet-2.0.0
/Users/travis/.nvm/versions/node/v10.9.0/bin/dotnet -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/call.js
/Users/travis/.nvm/versions/node/v10.9.0/bin/dotnet-run -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/call.js
/Users/travis/.nvm/versions/node/v10.9.0/bin/dotnet-run-2.0.0 -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/call.js
/Users/travis/.nvm/versions/node/v10.9.0/bin/install-dotnet-runtime -> /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0/dist/app.js
> dotnet-2.0.0@1.4.4 postinstall /Users/travis/.nvm/versions/node/v10.9.0/lib/node_modules/dotnet-2.0.0
> node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
+ dotnet-2.0.0@1.4.4
added 1 package in 5.286s
```

The tool works fine in Windows and Linux

#### System information
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102

**Comment by alopix** [comment]
Same issue installing without sudo on macOS:
`
yarn global add dotnet-2.0.0` results in:
```
yarn global v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error ~/.config/yarn/global/node_modules/dotnet-2.0.0: Command failed.
Exit code: 1
Command: node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
Arguments: 
Directory: ~/.config/yarn/global/node_modules/dotnet-2.0.0
Output:
Unable to install/use dotnet framework.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
